version: '3.5'
services: 
  apps:
    container_name: apps
    build:
      context: ./
      dockerfile: ./laravel/Dockerfile
      args:
        uid: ${PUID}
    working_dir: /apps
    volumes:
      - ./Apps:/apps
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      laravel:
        aliases:
          - apps

  apache:
    container_name: apache
    build:
      context: ./
      dockerfile: ./apache2/Dockerfile
    working_dir: /apps
    volumes:
      - ./Apps:/apps
    ports:
      - "${TEST_APP_PORT}:80"
      # - 8080: 8080
      # -  Add more ports here
    depends_on:
      - apps
    networks:
      laravel:
        aliases:
          - apache

  mysql:
    container_name: mysql
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes: 
      - dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      laravel:
        aliases:
          - mysql-db

networks:
  laravel:
    name: laravel

#Volumes
volumes:
  dbdata:
    driver: local
